### PR TITLE
Fix jumping action bar when popup overlay is active

### PR DESCRIPTION
**Pull request by aschempp**

### CODE REVIEW

**Comment by leofeyer** [comment]
@fritzmg has suggested a different fix in https://github.com/contao/contao/issues/704 🤷‍♂

**Comment by aschempp** [comment]
That's not the same thing. The action bar is the bottom bar with "Apply" or "Revert" buttons.

**Comment by aschempp** [comment]
FYI see https://github.com/contao/contao-manager/issues/234 for what you meant

**Comment by leofeyer** [comment]
I see. Never mind then. 😊

**Pull request merged**
