### PR TITLE
[WIP] Added provider config for Mittwald CM Service

### PR DESCRIPTION
**Pull request by thueske**
Hey!

Just added the provider config for Mittwald CM Service.

Would be very nice to see a new release with this change included.

Thanks!

Tobi

### CODE REVIEW

**Comment by leofeyer** [comment]
Why did you close the pull request?

**Comment by thueske** [comment]
Would like to test before :)

Should "mittwald.de" be the customers serverhost, domain or ....?

**Comment by leofeyer** [comment]
> Would like to test before :)

That's wise. 😄 

I have added the `[WIP]` prefix (work in progress) to the PR title, then the core developers know that the PR is not ready to be merged yet. We are using three prefixes:

* `[WIP]`: work in progress == please ignore
* `[RFC]`: request for comments == not finished, but please review and comment
* `[RTM]`: ready to merge == please review and merge

**Comment by leofeyer** [comment]
> Should "mittwald.de" be the customers serverhost, domain or ....?

@aschempp Can you answer this question please?

**Comment by thueske** [comment]
"Problem" is that IP adress equals the hostname when running the about command of the contao manager, so there is no real hostname.

Only the network name gives us information about the provider (AS15817 Mittwald CM Service GmbH und Co.KG.).

**Comment by aschempp** [comment]
If we have no hostname, the reverse IP lookup does not work, and therefore the provider detection never will. We can't really use that change then 😢

**Comment by thueske** [comment]
What do you think about adding the network name? E.g. for adding the name or only "AS15817" for example. @aschempp

**Comment by aschempp** [comment]
That does not really help, because some hosting providers share networks, afair that was the case for DomainFactory that was bought bei Host Europe.

**Comment by aschempp** [comment]
The solution will be to enter the binary path, or manually choose the hosting provider (in a later version). The detection does not help if it's arbitrary, we're already trying a lot of random PHP paths, just adding one for a network that can match multiple hosting setups does not help much.

**Comment by thueske** [comment]
Yes, that's my second solution. Thanks, then I will modify the manager.json file.

**Pull request closed without merging**
