### PR TITLE
Add ETES to the list of known hosting providers

### PR DESCRIPTION
**Pull request by sleitz**
I suspect the AS number is for automatic lookup of the matching provider? If so, I added our own AS.

### CODE REVIEW

**Comment by sleitz** [comment]
@aschempp Out of curiosity, what is the AS number for and why did you remove it in this case?

**Comment by aschempp** [comment]
https://en.wikipedia.org/wiki/Autonomous_system_(Internet)

We are using ipinfo.io for the provider list (https://ipinfo.io/hosting), ETES does not appear there.

**Comment by sleitz** [comment]
I cannot quite relate to that: https://ipinfo.io/AS205890 correctly shows our AS.

**Comment by sleitz** [comment]
As discussed in person, I did a test with the current stable version:

schritt-1

The first page (after login) does not select the correct settings. But switching to the second page:

schritt-2

Is this the correct behavior? Or should the settings be detected correctly in the first step? Would merging the AS number make a difference?

**Comment by aschempp** [comment]
No, it should automatically be detected (selected) in the second step. Was that the case?

**Comment by sleitz** [comment]
Yes, perfect. Thanks.

**Pull request merged**
