### PR TITLE
Patch 2 - french translation of fr.json

### PR DESCRIPTION
**Pull request by najbo**
All elements should be translated in french now.

### CODE REVIEW

**Comment by aschempp** [comment]
Translations are managed on Transifex (https://www.transifex.com/contao/contao-manager/). Please sign up for the french translation team and submit the changes over there.

**Comment by Toflar** [comment]
Should be mentioned in the README though :)

**Comment by najbo** [comment]
Yes ; so hätte ich nicht 2 Stunden verloren ;-)

**Comment by xchs** [comment]
> Translations are managed on Transifex (https://www.transifex.com/contao/contao-manager/). Please sign up for the french translation team and submit the changes over there.

Some time ago I had requested to join the German translation team for the Contao Manager project but that has been rejected now. So how should we proceed instead? Should we create a GitHub pull request for the `de.json` ?

**Comment by leofeyer** [comment]
We are managing the German translation ourselves. What did you want to change?

**Comment by xchs** [comment]
> What did you want to change?

See https://github.com/contao/contao-manager/pull/426

**Pull request closed without merging**
