### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by xchs**
Fixed some typos.

### CODE REVIEW

**Comment by aschempp** [comment]
Translations are managed on transifex.com, could you fix them there or should I adopt them?

**Comment by xchs** [comment]
@aschempp Yes, of course, I can also do this on Transifex. I have just submitted a request to join the team.

**Comment by aschempp** [comment]
Sorry about that, I just realized german is only translated by the Core team. I have adopted all your changes (except the neuste/neueste. We've discussed this at some point, and both versions are correct).

**Comment by xchs** [comment]
Thank you very much 👍🏻

**Pull request closed without merging**
