### PR TITLE
Fix the source language

### PR DESCRIPTION
**Pull request by leofeyer**
This PR aims to fix the source language.

### CODE REVIEW

**Comment by aschempp** [comment]
The API changes look good to me, but I dislike that you removed the **title case** in most of the labels. They are more readable to me, [best practice in Symfony documentation](https://symfony.com/doc/current/contributing/documentation/standards.html#english-language-standards) and sometimes even [recommended for titles](http://www.grammar-monster.com/lessons/capital_letters_title_case.htm)

**Comment by leofeyer** [comment]
Agreed for section titles. However, the following are not section titles, are they?

* More info
* More information
* Report a problem
* Install tool
* Rebuild cache
* Confirm & close
* Show console output
* Install packages
* Search packages
* Revert changes
* Check & install
* User account
* Retype password
* Expert settings
* GitHub token
* Create account
* Sign in

The only section titles I could find are:

* Starting Console Task …
* Setting up your Contao Application
* Updating Packages
* Installing Packages
* Removing Packages

But I guess you won't agree with me. 😄

**Comment by aschempp** [comment]
They are buttons, links or menu items, where the same thing applies in my opinion. Look at the footer navigation on www.apple.com for example, they apply title case as well.

**Comment by xchs** [comment]
> they use title case as well

… but they made also a little mistake. :)

Apart from this: I'd prefer Leo's version.

**Comment by leofeyer** [comment]
This is ready to merge now IMO. Please also update the Transifex sources afterwards.

**Pull request merged**
