### PR TITLE
Fix popup blocker for phpinfo

### PR DESCRIPTION
**Pull request by ausi**
This prevents the phpinfo link from being blocked by popup blockers.

@aschempp inline styles OK here?

And do we need to translate `loading...` ?

### CODE REVIEW

**Comment by ausi** [comment]
@aschempp should I rebase this on the develop branch?

**Comment by aschempp** [comment]
yes please rebase. Regarding the translation, I think it would not harm (and maybe write "Loading PHP Information"), wdyt?

**Comment by ausi** [comment]
Done.

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
Thank you @ausi

**Pull request merged**
