### PR TITLE
Add badge title support

### PR DESCRIPTION
**Pull request by zoglo**
Implements the badge_title into the Contao Manager.

### Description

- implements #816 

Also only allows one line of text and get's cut on mobile. I made sure to wrap it down when it get's too long. See the screenshots below

### Screenshots
image

**Mobile**
image
image

**Long badge in new row**
image

**Long badge**
image

**Lifestory badge**
image

### CODE REVIEW

**Comment by aschempp** [comment]
This does not use the config from Contao, right?

**Comment by zoglo** [comment]
It uses the manager.json, yeah.

**Comment by aschempp** [comment]
None of the json files are supposed to be edited by users atm, thats kinda why we have the manager in the first place 😅
But isn‘t there a route or already some ways to dump the container configuration? Something though the `ContaoConsole`?

**Comment by zoglo** [comment]
Didn't think of using the pup console rn. Been working within the app and there wasn't a route I could use.

You'd want it to match the same badge title as I'm contao, right?

**Comment by aschempp** [comment]
> You'd want it to match the same badge title as in contao, right?

Absolutely, anything else wouldn't make sense to me.

The API I was referring to is `/server/contao`. It already contains the `config` key (if supported by the given Contao version) 😎. Maybe you can try with that?

**Comment by zoglo** [comment]
Done - will only work when `debug:config --format` exists tho - most likely Symfony 6 aka Contao 5 :)

**Review by aschempp — CHANGES_REQUESTED** [review]
Looks good! However, if we ever skip the boot steps (there are plans to "improve reloading" in this regard), the badge title would be lost. Maybe `server/contao/` should store the badge title from the result, so we have it in the store already? And make sure `server/contao/get` is executed (but ignored because of cache by default) when the main app is loaded?

**Review by aschempp — APPROVED** [review]

**Comment by aschempp** [comment]
Thank you @zoglo

**Pull request merged**
